### ISSUE TITLE
How to walk the AST produced by parse or parse_file?

### ISSUE THREAD

**Issue by rookiekuan** [ConsenSys/python-solidity-parser#10]
I just don't know the meaning that the second param named "callback_object" in function "visit" of parser.py in this module. How can I leverage this function to walk the AST produced by parse or parse_file? Or maybe other more useful methods to apply to this.

**Comment by tintinweb** [comment]
Hi @rookiekuan,

There are some examples on how to manually walk the AST in the [README](https://github.com/ConsenSys/python-solidity-parser/blob/master/README.md) and the [__main__](https://github.com/ConsenSys/python-solidity-parser/blob/master/solidity_parser/__main__.py) file. Another option is to create your own [visitor](https://github.com/ConsenSys/python-solidity-parser/blob/master/solidity_parser/parser.py#L1060).

hope that helps.
cheers,
tin
