### ISSUE TITLE
Parsing the acquired object is not serializable

### ISSUE THREAD

**Issue by litcc** [ConsenSys/python-solidity-parser#26]
This code does not execute and cannot serialize the variable kk2, making it impossible to transfer this data between multiple python processes

```python

from solidity_parser import parse_file,objectify
import pickle

if __name__ == "__main__":
    print("Hello World!")
    kk = parse_file(path="samples/simple.sol")
    kk2 = objectify(kk)
    k3 = pickle.dumps(kk2)
    print(k3)

```

**Comment by benharbit** [comment]
How do you solve this problem?

**Comment by litcc** [comment]
Oh, and this is a bit old, I forget exactly, it's possible that parse_file(path) is being used instead of parse(text)

**Comment by benharbit** [comment]
it turns out you can use the multiprocessing library in python 3.11 and not 3.9 because 3.11 defines __setstate__ and __getstate__.   If you are are using a python version less than 3.11 you can just add __setstate__ and __getstate__ to the parser Class Node
