### ISSUE TITLE
About 1/6 of mainnet contracts can not be parsed using this parser.

### ISSUE THREAD

**Issue by xoredtwice** [ConsenSys/python-solidity-parser#8]
I used [smart contract sanctuary](https://github.com/tintinweb/smart-contract-sanctuary) to dump all mainnet solidity contracts (32382 contracts at the moment of dumping without removing duplicates).

Then I iterated over it and used your parser. This spreadsheet is list of all contracts that could not be parsed. (detected using exception handler). About 5K of contracts could not be parsed. 

Hope it will be helpful.

[solidity_parser_mainnet_32382_errors.zip](https://github.com/ConsenSys/python-solidity-parser/files/4177158/solidity_parser_mainnet_32382_errors.zip)

**Comment by shayanb** [comment]
Thanks @xoredtwice. Is it possible to include the exception error in the file too? I see that it only has the file names.

**Comment by xoredtwice** [comment]
Thanks for reply @shayanb . I exported just the filenames (including contract address). I will run the script again and share another spreadsheet soon with the exceptions' detail. 

P.S. 
The last line of python-solidity-parser Readme says: "Update the grammar in ./solidity-antlr4/Solidity.g4 and run the antlr generator script to create the parser classes in solidity_parser/solidity_antlr4."

I am using default grammar for parsing. I just downloaded the package and used:
parser.parse_file(contract)

Maybe that's the problem?

**Comment by GNSPS** [comment]
Yeah, that's definitely a very dated version of the grammar. Let's change the grammar submodule to the one we're maintaining now @ https://github.com/ConsenSys/solidity-antlr4 😄 🎉

**Comment by xoredtwice** [comment]
Thanks for your reply.

The problem was with [smart contract sanctuary](https://github.com/tintinweb/smart-contract-sanctuary) dump. Single quotation characters have been replaced with "&#39;".  I will add an issue to that project.

After fixing this issue, there are only 65 mainnet solidity contracts can not be parsed with your AST parser. I have not changed the grammar. After a glance over the error, it seems that some of them still have character replacement issues for other characters.

I will update the grammar but 65 errors in 32K is pretty awesome. My application can tolerate it. 
Best Solidity Parser ever. Congrats guys. :)

[error_logs_32382_65.txt](https://github.com/ConsenSys/python-solidity-parser/files/4182489/error_logs_32382_65.txt)
